### ISSUE TITLE
sane escape codes

### ISSUE THREAD

**Issue by tbodt** [legolord208/termplay#1]
like alternate screen mode and hide cursor during playback, and reset cursor to top left before each frame

why did I have to explain that you're psychic and you just know

**Comment by jD91mZM2** [comment]
> you're psychic

also referred to as "having communication using another service than GitHub issues, for example Discord, because we are friends". But that's longer to say I guess

**Comment by tbodt** [comment]
typing is hard

**Comment by jD91mZM2** [comment]
TIP: Don't hurry yourself like you always do because that gets very tiring. Type jjjuuuuussttt a bit slower, and it will feel easier. Take your time :)
