### ISSUE TITLE
Process video frames to text in real-time

### ISSUE THREAD

**Issue by ritiek** [legolord208/termplay#10]
It would be nice if the video frames could be processed to text in real-time without having the tool process all of them at initialization causing a lot of wait with long videos.

**Comment by jD91mZM2** [comment]
While I agree, it's also kind of risky. What happens if it hits the end (video playing too fast)?

For now, I'd recommend setting up a quick script to cut whatever you're watching into short fragments first (via ffmpeg), and perhaps even pre-process stuff behind the scenes.

**Comment by ritiek** [comment]
I think it should just wait until the next frame is processed. Yep, I do realize that this is going to be a bit risky, maybe we could have an option whether to process video frames real time or all of them at initialization.

**Comment by jD91mZM2** [comment]
But, how do I know if I want to wait for the next frame or if it's done? Do I have a timeout?

**Comment by ritiek** [comment]
I am not sure at the moment. I do not yet know how exactly this tool works. I'll study the source code and see if there is a way out.

**Comment by jD91mZM2** [comment]
Hmmm. To be honest, the biggest reason I haven't done this is because I feel like the code would be pretty messy

**Comment by tbodt** [comment]
Also you're going to have to deal with the sound playing library, which has a very simple API that might make it hard to accurate pause and resume the audio.

**Comment by jD91mZM2** [comment]
I considered that, but then I realized that I already have pause (press space while playing), and that seems to work fine.

**Comment by tbodt** [comment]
Just checked the API, and it has play and pause methods, but no method to set the playback position. This can work, but it'll drift.

**Comment by jD91mZM2** [comment]
Ok, so I tried making a basic bash script to start a pre-processing in the background (and slightly modified termplay to convert the audio before the images), and play at the same time.
It worked fine for small videos, but it raised a lot of questions:

- How do we know the amount of frames? Do we just play until it hits a timeout?
- In 60 FPS videos, it doesn't take long at all for the playback to catch up with the processing. Is this an important feature?
- What do we do if there's an error? The view will completely mess up!

**Comment by jD91mZM2** [comment]
The rewrite will support this. It's easier to design something like this from the core up, and I decided to scrap the code anyways since it's quite messy.

**Comment by jD91mZM2** [comment]
Rewrite now uses gstreamer, a proper video streaming library, and converts it on-the-fly. Check out the `rewrite` branch :)
