### ISSUE TITLE
Feature request: double vertical resolution using unicode half blocks

### ISSUE THREAD

**Issue by nikamarisa** [legolord208/termplay#11]
It would be nice to have double the vertical resolution by using either ▀ (U+2580, Upper half block) or  ▄ (U+2584, Lower half block) in combination with both settion fore- and background color.

For example, sending `\e[48;5;9m\e38;5;10m▄` to the terminal will show the upper half red and the lower half green.

Additionally, those half blocks are usually much closer to a square than a space is.

Naively one would do something along the lines of:
```
if y%2 == 0 {
        for x in 0..image.width() {
                let pixel = image.get_pixel(x, y);
                let lower_pixel = image.get_pixel(x, y+1);
                let channels = pixel.channels();
                let lower_channels = lower_pixel.channels();
                use std::fmt::Write;
                write!(result, "\x1b[48;2;{};{};{}m\x1b[38;2;{};{};{}m▄", 
                        channels[0], channels[1], channels[2], 
                        lower_channels[0], lower_channels[1], lower_channels[2]).unwrap();
        }
}
```
However, this will fail if the height of the input is an uneven number of pixels, since it will try to read out of bonds.

Sadly, I don't actually know Rust and have no idea, how to fix this 😒

**Comment by jD91mZM2** [comment]
I like it! I'm a little concernced how it will go with ratios and stuff like that, but it's definitely worth a shot!

**Comment by jD91mZM2** [comment]
This is now supporter in the rewrite. I love you for the idea, because everything has a so much better resolution now. Thanks <3
