### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by ghost** [legolord208/termplay#12]
Hi,

I followed and Installed the required Libraries as you mentioned in README.md,
`apt install libopenal-dev libsndfile1-dev libgstreamer1.0-dev libsixel-dev`

but I get this:

`error: failed to run custom build command for `gstreamer-app-sys v0.5.0`
process didn't exit successfully: `/tmp/cargo-install.UHVy5JJj1usQ/release/build/gstreamer-app-sys-9fd3835cd27cf2c1/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gstreamer-app-1.0 >= 1.8"` did not exit successfully: exit code: 1
--- stderr
Package gstreamer-app-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-app-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-app-1.0' found

warning: build failed, waiting for other jobs to finish...
error: failed to compile `termplay v2.0.2`, intermediate artifacts can be found at `/tmp/cargo-install.UHVy5JJj1usQ`

My RustC version is `rustc 1.24.1`

**Comment by jD91mZM2** [comment]
Ah yes, I forgot to specify the dependency on `gst-plugins-base` and `gst-plugins-bad`. Does installing those two work?

**Comment by ghost** [comment]
I installed the two deps `apt install gstreamer1.0-plugins-bad gstreamer1.0-plugins-base`

Still nothing, I get exactly the same error.

**Comment by jD91mZM2** [comment]
I'm not completely sure. Is `gstreamer-app-1.0` available to install? Also, what version of Ubuntu are you on? I know that on Travis I had issues with packages being outdated.

**Comment by ghost** [comment]
tried it on Ubuntu Bionic Beaver 18.04, and Installed everything
`apt install libopenal-dev libsndfile1-dev libgstreamer1.0-dev libsixel-dev gstreamer1.0-plugins-bad gstreamer1.0-plugins-base`

Still not compiling and I have the same error.

The `gstreamer-app-1.0` is already installed in almost every distro.

**Comment by jD91mZM2** [comment]
Ah, since Ubuntu separates binary and header packages, you need `libgstreamer-plugins-base1.0-dev` and `libgstreamer-plugins-bad1.0-dev`

**Comment by jD91mZM2** [comment]
Did that fix it?

**Comment by jD91mZM2** [comment]
Closed due to inactivity
