### ISSUE TITLE
Update install instructions

### ISSUE THREAD

**Issue by enedil** [legolord208/termplay#2]
Hello guy,
I tried compiling this project with cargo. Your install instruction just tells `cargo build --release`, because you probably don't realise you use some shared libraries already present on your system. Anyway, that's what I got on Fedora 25:
```
 = note: /usr/bin/ld: cannot find -lopenal
/usr/bin/ld: cannot find -lsndfile
collect2: error: ld returned 1 exit statu
```

**Comment by tbodt** [comment]
Ah, you're going to have to install openal and libsndfile...that is worth mentioning.

**Comment by tbodt** [comment]
Well it does say

> The only external package libraries needed to install are the ones required by [ears](https://github.com/jhasse/ears).

**Comment by jD91mZM2** [comment]
Thanks for answering this for me while I was asleep @tbodt :)
