### ISSUE TITLE
It would be great to have libsixel support

### ISSUE THREAD

**Issue by vrthra** [legolord208/termplay#3]
It would be great to have [libsixel](https://github.com/saitoha/libsixel) support. Most modern terminals such as Xterm can be started up with the Sixel support. For example, [here](http://imgur.com/281Li5e) is an example of a gif playing in xterm stared with sixel support.

**Comment by jD91mZM2** [comment]
OOooo!! I've been looking for a library to actually draw real images! Thanks for informing me of one :)

**Comment by tbodt** [comment]
But it doesn't work on every terminal...i.e. doesn't work on any of the terminals I use.

**Comment by jD91mZM2** [comment]
@tbodt Of course it'll be optional :P

**Comment by legolord208** [comment]
After some looking around, I found that

**Comment by jD91mZM2** [comment]
After looking around, I found [rust-sixel](https://github.com/meh/rust-sixel)... A pure Rust sixel library.
Except, it uses a different image library than me :|

There is also [sixel-sys](https://github.com/AdnoC/sixel-sys), but that doesn't seem to supply all `Encoder` fields, which I probably need to actually get the output.
EDIT: Ohhh, no! It still supports `sixel_encoder_setopt` so I can redirect it to any stream I want. Cool!

Any suggestion on what I should do? Should I implement them using FFI myself?

**Comment by vrthra** [comment]
I haven't worked with Rust before, so I have no suggestion here :(

**Comment by jD91mZM2** [comment]
Okay! I'll see what I can do :)

EDIT: Have been kinda busy today. I will get this done, though

**Comment by jD91mZM2** [comment]
OMG IT WORKS!

I just need to make it scale like it should, and then it actually works!!!!!!!!!!!!!!!
