### ISSUE TITLE
Improve installation method?

### ISSUE THREAD

**Issue by ghost** [legolord208/termplay#4]
Why do we need to clone the repo to install doesn't cargo already provide an install command to install executable packages?
Something in the lines of this,
`cargo install termplay`

As I've done it in this library.
https://github.com/pyros2097/rust-embed

**Comment by ghost** [comment]
Btw Great work.. Love this tool... I'm an core terminal user, I do everything in a terminal from file mangers to editors and image viewers the only thing I lacked was an ability to play videos in terminal and this solves it. Only wish it could be improved to a normal quality like how w3m manages to display images properly in ranger.

**Comment by jD91mZM2** [comment]
Ohh! Thanks a lot for the feedback :)

Before I answer the actual issue, I just wanted to state that real images are probably coming. See Issue #3. Sadly not all terminals will support it.

Secondly, I will probably provide pre-built binaries for Windows and Linux in the future.

**Comment by jD91mZM2** [comment]
Oops sorry for closing. My mistake

**Comment by tbodt** [comment]
To get cargo install, I think you just have to upload the project as a crate.

**Comment by jD91mZM2** [comment]
I know, thanks. Doing so ATM
