### ISSUE TITLE
Installation error : unreachable pattern

### ISSUE THREAD

**Issue by al-ramadhan** [legolord208/termplay#6]
Hi,

It's my first time install termplay and got this error

`error[E0001]: unreachable pattern
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.14.0/./src/dynimage.rs:641:9
    |
641 |         _ => Err(image::ImageError::UnsupportedError(format!("A decoder for {:?} is not available.", format))),
    |         ^ this is an unreachable pattern
`

Any missing there?
Need help please

**Comment by jD91mZM2** [comment]
That seems to be a problem with a dependency... Hmmm.... Which Rust version do you use?

**Comment by al-ramadhan** [comment]
Its rustc 1.15.1

**Comment by jD91mZM2** [comment]
Aha. Try upgrading Rust by running `rustup update stable`. Cheers!
