### ISSUE TITLE
Failed. Retrying

### ISSUE THREAD

**Issue by ghost** [legolord208/termplay#8]
Creating directory...
Starting conversion: Video -> Image...
Started new process.
Converting: Image -> Text
Processing frame1.png
Failed. Retrying...
Processing frame1.png
Failed. Retrying...
Processing frame1.png
Failed. Retrying...
Processing frame1.png
I have tried 3 times, still can't read the file.
Did ffmpeg hang? Are you trolling me by deleting files?
I give up. Error: Format error: unexpected EOF

**Comment by jD91mZM2** [comment]
What operating system is this?  
What is the command are you running (it's OK to censor video name or url if you want to of course)?

**Comment by jD91mZM2** [comment]
@datxinitric

**Comment by ghost** [comment]
Don't know how but this error has gone but I got a new error saying: no space left on drive. But I have space on drive.

**Comment by ghost** [comment]
probably a bug.

**Comment by jD91mZM2** [comment]
If it says there is no space on the drive, it's probably true. The error is coming from the operating system itself. Perhaps your temp folder is stored on a different drive than you think.

**Comment by ritiek** [comment]
@datxinitric What is the output of `df -h`?

**Comment by ghost** [comment]
Video does not exist.
